// app/domains/page.jsx — All 8 Domain Hubs with live Notion task counts

const NOTION_API = 'https://api.notion.com/v1';
const TASKS_DB = 'd0df52150e60480b991ea8d875de5c9e';

const DOMAINS = [
  { id:'insurance', emoji:'💼', name:'Insurance', subtitle:'Armor Insurance Pro', note:'Boss: Davin', desc:'Life insurance · Clients & policies · Lead websites · Scripts · Onboarding checklist', notionUrl:'https://www.notion.so/33683fbef7cf8118baffeb340c6731b6', area:'Insurance' },
    { id:'vnd', emoji:'👗', name:'Vixens N Darlings', subtitle:'My Company', note:'Founder: Tiffany', desc:'Pitch competition · Brand · Legal (USPTO) · Sourcing · Faire wholesale', notionUrl:'https://www.notion.so/33683fbef7cf814ca6b0fbc28021b9c2', area:'V&D' },
      { id:'content', emoji:'📱', name:'tunedinwithtiff', subtitle:'Personal Brand', note:'@tunedinwithtiff', desc:'Hooks · Science-backed education series · BTS Founder · Day in my life / GRWM', notionUrl:'https://www.notion.so/33783fbef7cf81ce82d4d280460396a5', area:'Social media' },
        { id:'ypo', emoji:'🤝', name:'YPO / EO', subtitle:'Mentorship Program', note:'With: Justin · Sergei (EO) · Tarina (YNG)', desc:'EO + YNG mentees · Gratitude Gala May 15 · Mentors: Noah, Mike, Steve, Mark', notionUrl:'https://www.notion.so/33683fbef7cf81ca870ee859b3fa43fd', area:'YPO' },
          { id:'cafe', emoji:'☕', name:'Café — As Brew', subtitle:'Mon & Thu mornings', note:'Boss: Philip', desc:'Operations · Barista Bible · Opening checklist · Side tasks', notionUrl:'https://www.notion.so/33683fbef7cf81b08b1cc7136bab1b52', area:'Cafe' },
            { id:'school', emoji:'🎓', name:'School & Scholarships', subtitle:'ASU · Thunderbird', note:'Track deadlines', desc:'Scholarship applications · Essay bank · Transcripts · Academic research', notionUrl:'https://www.notion.so/33783fbef7cf8127be32d9b3a0b603be', area:'Academic' },
              { id:'docs', emoji:'📂', name:'Personal Documents', subtitle:'Everything tagged & linked', note:'Resume · Transcript · Cover Letters · Legal · ID', desc:'Tagged: #resume #transcript #coverletter #id #financial #vnd — find anything instantly', notionUrl:'https://www.notion.so/33783fbef7cf819692a3dd1b98b73a38', area:null },
                { id:'money', emoji:'💰', name:'Money', subtitle:'Income & Finances', note:'Track everything', desc:'Income tracking · Commissions · Direct deposit · Budgeting', notionUrl:'https://www.notion.so/cce0f44c7ebd4b4e850b05d9c693d535', area:null },
                ];

                async function getTaskCounts() {
                  try {
                      const apiKey = process.env.NOTION_API_KEY;
                          if (!apiKey) return {};
                              const res = await fetch(NOTION_API + '/databases/' + TASKS_DB + '/query', {
                                    method: 'POST',
                                          headers: { Authorization: 'Bearer ' + apiKey, 'Content-Type': 'application/json', 'Notion-Version': '2022-06-28' },
                                                body: JSON.stringify({ filter: { property: 'Status', select: { does_not_equal: 'Done' } }, page_size: 100 }),
                                                      next: { revalidate: 60 },
                                                          });
                                                              if (!res.ok) return {};
                                                                  const data = await res.json();
                                                                      const counts = {};
                                                                          for (const task of data.results) {
                                                                                const area = task.properties?.Area?.select?.name;
                                                                                      if (area) counts[area] = (counts[area] || 0) + 1;
                                                                                          }
                                                                                              return counts;
                                                                                                } catch {
                                                                                                    return {};
                                                                                                      }
                                                                                                      }

                                                                                                      export default async function DomainsPage() {
                                                                                                        const counts = await getTaskCounts();
                                                                                                          return (
                                                                                                              <div style={{ minHeight: '100vh', background: '#f8f6f2', fontFamily: 'system-ui, sans-serif' }}>
                                                                                                                    <div style={{ maxWidth: '1100px', margin: '0 auto', padding: '40px 24px' }}>
                                                                                                                            <div style={{ marginBottom: '32px' }}>
                                                                                                                                      <h1 style={{ fontSize: '28px', fontWeight: 800, color: '#1a1a1a', margin: 0 }}>
                                                                                                                                                  🧠 Tiff&apos;s Second Brain
                                                                                                                                                            </h1>
                                                                                                                                                                      <p style={{ color: '#777', marginTop: '6px', fontSize: '15px' }}>
                                                                                                                                                                                  All 8 domains — live task counts from Notion
                                                                                                                                                                                            </p>
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '16px' }}>
                                                                                                                                                                                                                      {DOMAINS.map((d) => {
                                                                                                                                                                                                                                  const n = d.area ? counts[d.area] || 0 : null;
                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                            <div key={d.id} style={{ background: '#fff', borderRadius: '12px', padding: '24px', border: '1px solid #e8e4df', display: 'flex', flexDirection: 'column', gap: '8px' }}>
                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: '30px', lineHeight: 1, marginBottom: '8px' }}>{d.emoji}</div>
                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '17px', fontWeight: 700, color: '#1a1a1a' }}>{d.name}</div>
                                                                                                                                                                                                                                                                                                                                                          <div style={{ fontSize: '12px', color: '#999', marginTop: '2px' }}>{d.subtitle}</div>
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                              {n !== null && (
                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{ background: n > 0 ? '#fff3f0' : '#f0fff4', color: n > 0 ? '#c0392b' : '#27ae60', fontSize: '11px', fontWeight: 600, padding: '3px 8px', borderRadius: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                        {n > 0 ? n + ' task' + (n !== 1 ? 's' : '') : '✓ clear'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: '12px', color: '#777', fontStyle: 'italic' }}>{d.note}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: '13px', color: '#555', lineHeight: 1.6 }}>{d.desc}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href={d.notionUrl} target="_blank" rel="noopener noreferrer" style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', marginTop: '8px', padding: '8px 14px', background: '#1a1a1a', color: '#fff', borderRadius: '8px', fontSize: '13px', fontWeight: 600, textDecoration: 'none' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Open in Notion →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ textAlign: 'center', padding: '24px', color: '#bbb', fontSize: '12px' }}>Tiff&apos;s Second Brain · All domains synced from Notion</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }